/** Date pentru afișarea pachetelor (landing + dashboard plan) */
export const PLANS_DISPLAY = [
  {
    id: 'free' as const,
    name: 'Free',
    badge: null as string | null,
    priceMonthly: 0,
    priceAnnual: 0,
    priceAnnualPerMonth: 0,
    forever: true,
    features: [
      '1 client activ',
      'Până la 3 rapoarte/lună',
      'Google Ads + Meta Ads',
      'Watermark "Powered by REPORTKIT" pe PDF',
      'Email support (48h response)',
    ],
    cta: 'Începe gratuit',
  },
  {
    id: 'starter' as const,
    name: 'Starter',
    badge: null as string | null,
    priceMonthly: 19,
    priceAnnual: 171,
    priceAnnualPerMonth: 14.25,
    forever: false,
    features: [
      'Până la 5 clienți activi',
      'Rapoarte PDF nelimitate',
      'Google Ads + Meta Ads',
      'White-label (fără watermark)',
      'Email support (24h response)',
    ],
    cta: 'Alege Starter',
  },
  {
    id: 'professional' as const,
    name: 'Professional',
    badge: 'Cel mai popular' as string | null,
    priceMonthly: 69,
    priceAnnual: 621,
    priceAnnualPerMonth: 51.75,
    forever: false,
    features: [
      'Până la 20 clienți activi',
      'Rapoarte PDF nelimitate',
      'Google Ads + Meta Ads + Google Analytics 4',
      'Full white-label (logo + culori personalizate)',
      'Rapoarte programate automat (trimise pe email lunar)',
      'Priority email support (12h response)',
    ],
    cta: 'Alege Professional',
  },
  {
    id: 'agency' as const,
    name: 'Agency',
    badge: null as string | null,
    priceMonthly: 149,
    priceAnnual: 1341,
    priceAnnualPerMonth: 111.75,
    forever: false,
    features: [
      'Clienți nelimitați',
      'Toate platformele (Google Ads, Meta Ads, GA4, + altele când adaugi)',
      'Full white-label + Custom domain (ex: reports.agencyname.com)',
      'Rapoarte programate + auto-trimise pe email',
      'Priority support (6h response) + onboarding call',
      'Dedicated account manager',
    ],
    cta: 'Alege Agency',
  },
] as const;

export type PlanDisplayId = (typeof PLANS_DISPLAY)[number]['id'];
